name: 'Generate Class Diagram'

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'

jobs:
  generate-class-diagram:
    name: 'Generate Class Diagram'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz
          wget -O plantuml.jar https://sourceforge.net/projects/plantuml/files/plantuml.jar/download
          
      - name: Generate Class Diagram
        run: |
          mkdir -p docs/diagrams
          find src/backend -name "*.cs" | xargs grep -l "class\|interface" | xargs cat > class_files.txt
          java -jar plantuml.jar -tpng -o ../docs/diagrams class_files.txt
          
      - name: Commit and Push Diagram
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/diagrams/
          git commit -m "Update class diagram" || echo "No changes to commit"
          git push